### ISSUE TITLE
cmsmap.map import error

### ISSUE THREAD

**Issue by jorditorresb** [Dionach/CMSmap#10]
Last version Kali and CMSmap

root@kali:~/CMSmap# python cmsmap.py -t https://example.com
Traceback (most recent call last):
  File "cmsmap.py", line 4, in <module>
    from cmsmap.main import main
  File "/root/CMSmap/cmsmap/main.py", line 4, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

Anu help?

**Comment by UmerYousuf** [comment]
did you 

> Last version Kali and CMSmap
> 
> root@kali:~/CMSmap# python cmsmap.py -t https://example.com
> Traceback (most recent call last):
> File "cmsmap.py", line 4, in
> from cmsmap.main import main
> File "/root/CMSmap/cmsmap/main.py", line 4, in
> from urllib.parse import urlparse
> ImportError: No module named parse
> 
> Anu help?

have you find any solution on this ??

**Comment by moseswynn** [comment]
This is likely a version issue. Please confirm you are running with Python 3.
