### ISSUE TITLE
Exception when bruteforcing Wordpress site.

### ISSUE THREAD

**Issue by LutherWest** [Dionach/CMSmap#11]
[-] Date & Time: 20/06/2015 10:01:01
[-] Wordpress Brute Forcing Attack Started
Traceback (most recent call last):
  File "cmsmap.py", line 2008, in <module>
    bruter.Start()
  File "cmsmap.py", line 1249, in Start
    self.WPXMLRPC_brute()
  File "cmsmap.py", line 1265, in WPXMLRPC_brute
    for pwd in self.pswlist:
TypeError: 'NoneType' object is not iterable

It doesn't work with any wordlist file, I've attempted rockyou.txt and darkc0de.lst

Please assist.

EDIT: forgot to add the command line:

sudo python cmsmap.py -t http://somesite/wordpress/ -f W -u username -w ~/darkc0de.lst

**Comment by LutherWest** [comment]
SOLVED....

I put the incorrect argument. Instead of -w ~/darkc0de.lst it should be -p ~/darkc0de.lst

Sorry for the retarded posted issue.
