### ISSUE TITLE
bruter.WPXMLRPC_brute() issue

### ISSUE THREAD

**Issue by xittna** [Dionach/CMSmap#14]
I'm not a python programmer, but I love this tool.  When running this I kept getting the same types of errors:

Traceback (most recent call last):
  File "./cmsmap.py", line 2033, in <module>
    scanner.ForceCMSType()
  File "./cmsmap.py", line 194, in ForceCMSType
    WPScan(self.url,self.threads).WPrun()
  File "./cmsmap.py", line 357, in WPrun
    bruter.WPXMLRPC_brute()
  File "./cmsmap.py", line 1274, in WPXMLRPC_brute
    htmltext = opener.open(req).read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: www.example.com/xmlrpc.php

I was able to get the full scan to run by commenting out line 357.  I don't really need the brute.WPXMLRPC output.  I ran this on multiple machines and got the same output.

**Comment by lucidtrip** [comment]
i dont no but try: "**http**://www.example.com/xmlrpc.php" with "**http**".
