### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by DrRem** [dionach/CMSmap#15]
## Issue Details
CMSmap Version: 1.0 
CMS Type:   
CMS Version:  
Plugin Name:  
OS Information:  windows 10 Enterprise Edition 1903

## Steps to reproduce the issue

py cmamap.py target

## Expected behaviour 

Traceback (most recent call last):
  File "cmsmap.py", line 4, in <module>
    from cmsmap.main import main
  File "E:\CMSmap\cmsmap\main.py", line 9, in <module>
    from .lib.scanner import scanner
  File "E:\CMSmap\cmsmap\lib\scanner.py", line 7, in <module>
    from .wpscan import wpscan
  File "E:\CMSmap\cmsmap\lib\wpscan.py", line 344, in <module>
    wpscan = WPScan()
  File "E:\CMSmap\cmsmap\lib\wpscan.py", line 35, in __init__
    self.themes = [line.strip() for line in open(initializer.wp_themes)]
  File "E:\CMSmap\cmsmap\lib\wpscan.py", line 35, in <listcomp>
    self.themes = [line.strip() for line in open(initializer.wp_themes)]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 4899: illegal multibyte sequence

**Comment by DrRem** [comment]
Is it due to the lack of some packages?
