### ISSUE TITLE
TypeError: gethostbyname

### ISSUE THREAD

**Issue by dpuls** [dionach/CMSmap#17]
## Issue Details
CMSmap Version:  v1.0
CMS Type:  non specified
CMS Version:  
Plugin Name:  
OS Information:  Kali latest

## Steps to reproduce the issue

root@kali:~/CMSmap# cmsmap webserver.here
[-] Date & Time: 12/12/2019 21:38:25
Traceback (most recent call last):
  File "/usr/local/bin/cmsmap", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cmsmap/main.py", line 168, in main
    addr = socket.gethostbyname(urlparse(args.target).hostname)
TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None

Describe how to reproduce the issue

## Expected behaviour 

Describe how CMSmap should have handled the issue

**Comment by LizardBlizzard** [comment]
You'll get this error if you don't specify a full URL.
Instead of `cmsmap example.com` try `cmsmap https://example.com`
