### ISSUE TITLE
Joomla scanning HTTPS error

### ISSUE THREAD

**Issue by seefor** [Dionach/CMSmap#22]
I got this error testing is on Kali 2.0:
[I] Joomla Website Template: logistix
Traceback (most recent call last):
  File "cmsmap.py", line 2033, in <module>
    scanner.ForceCMSType()
  File "cmsmap.py", line 196, in ForceCMSType
    JooScan(self.url,self.threads).Joorun()
  File "cmsmap.py", line 677, in Joorun
    self.JooTemplate()
  File "cmsmap.py", line 718, in JooTemplate
    if AdminTemplate[0] : 
IndexError: list index out of range

Thanks,
Sif

**Comment by greengeek1** [comment]
I got this identical error as well after trying to scan my joomla site in Kali 2.0 using only the -t argument with the website url.
