### ISSUE TITLE
Exceptions not handled

### ISSUE THREAD

**Issue by harshadyeola** [Dionach/CMSmap#22]
Thanks For this wonderful tool :+1: .  Came across this exception, leaving space for improvement.

```bash
./cmsmap.py -t http://example.com -f W        
Traceback (most recent call last):
  File "./cmsmap.py", line 1881, in <module>
    scanner.NotExisitingCode()
  File "./cmsmap.py", line 303, in NotExisitingCode
    htmltext = noRedirOpener.open(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>
```

**Comment by m7x** [comment]
thanks for reporting this issue. I've add an exception for it.
