### ISSUE TITLE
when i run the cmsmap I get the following request

### ISSUE THREAD

**Issue by aashish22** [dionach/CMSmap#24]
## Issue Details
CMSmap Version:  
CMS Type:  
CMS Version:  
Plugin Name:  
OS Information:  

## Steps to reproduce the issue

Describe how to reproduce the issue

## Expected behaviour 

Describe how CMSmap should have handled the issue

**Comment by aashish22** [comment]
Traceback (most recent call last):
  File "cmsmap.py", line 25, in <module>
    main()
  File "/root/CMSmap/cmsmap/main.py", line 119, in main
    if url.endswith("/"):
AttributeError: 'NoneType' object has no attribute 'endswith'

I get this error while i run cmsmap

**Comment by l3ragio** [comment]
Be careful, use the right syntax while starting the tool
e.g.

`python3 cmscan.py "http://example.com"`

You are likely adding some flag (e.g., "-u") before the URL.
