### ISSUE TITLE
Error when serarching for wordpress plugin

### ISSUE THREAD

**Issue by manhtet** [Dionach/CMSmap#26]
┌──(root💀localhost)-[/home/kali/CMSmap]
└─# python3 cmsmap.py https://hackertarget.com
[-] Date & Time: 04/06/2021 20:03:46
[I] Threads: 5
[-] Target: https://hackertarget.com (35.190.61.45)
[I] Server: nginx
[L] X-Frame-Options: Not Enforced
[I] X-Content-Security-Policy: Not Enforced
[L] Robots.txt Found: https://hackertarget.com/robots.txt
[I] CMS Detection: WordPress                                                            [-] WordPress usernames identified:
[M] jody-admin
[M] the admin
[M] XML-RPC services are enabled
[I] Autocomplete Off Not Found: https://hackertarget.com/wp-login.php
[-] Default WordPress Files:
[-] Searching Wordpress Plugins ...
80%Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/kali/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run
    requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None)
  File "/home/kali/CMSmap/cmsmap/lib/requester.py", line 31, in request
    self.response = urllib.request.urlopen(self.req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)                                                                  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.8/http/client.py", line 1100, in putrequest
    self._validate_path(url)
  File "/usr/lib/python3.8/http/client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/wp-content/plugins/worprees plugin bug dar/' (found at least ' ')
99%^

**Comment by Dl1ruv** [comment]
To fix this error change the cmsmap/data/wp_plugins_small.txt at line 372 and replace from worprees plugin bug dar to wordpress_plugin_bug_dar that should solve the problem. I hope it helps.
