### ISSUE TITLE
BruteForce exception : AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by aminehmida** [Dionach/CMSmap#27]
This is the exception :
```
Traceback (most recent call last):
  File "./cmsmap.py", line 1971, in <module>
    scanner.FindCMSType()
  File "./cmsmap.py", line 233, in FindCMSType
    JooScan(self.url,self.threads).Joorun()
  File "./cmsmap.py", line 680, in Joorun
    BruteForcer(self.url,self.usernames,self.weakpsw).Joorun()
  File "./cmsmap.py", line 1285, in Joorun
    token = reg.search(htmltext).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Maybe you should check the result of `reg.search before` calling `group(1)`

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
