### ISSUE TITLE
Joomla scan error: Exception in thread Thread-5, TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by natv** [Dionach/CMSmap#30]
Running on Python 2.7

Trying to scan a Joomla site, she script errors and then hangs here:

[-] Searching Joomla Components ...
62%Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

100%

**Comment by Shazgul** [comment]
Got also such an problem:

[-] Searching Joomla Components ...
2%Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

26%Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

33%

**Comment by jcherqui** [comment]
Same error

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable
```
