### ISSUE TITLE
Some errors while running the scan.

### ISSUE THREAD

**Issue by samerxx** [Dionach/CMSmap#32]
./cmsmap.py -t http://[...] -f W -F -v

[-] Interesting Directories/Files ... 
Exception in thread Thread-3:      |---------                                                                                                                                            | ETA:  00:01:10  23.41 B/s
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./cmsmap.py", line 1185, in run
    noRedirOpener.open(req); self.pluginsFound.append(plugin)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by c0ldb00t3r** [comment]
same issue i'm also facing stopped in 24%

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
