### ISSUE TITLE
CMSMap under Windows

### ISSUE THREAD

**Issue by pedrodj** [Dionach/CMSmap#33]
Hi,

C:\Python34>python.exe C:\Users\Pedro\Downloads\CMSmap-master1\CMSmap-master\cms
map.py
  File "C:\Users\Pedro\Downloads\CMSmap-master1\CMSmap-master\cmsmap.py", line 4
3
    print "[!] Git Repository Not Found. Please download the latest version of C
MSmap from GitHub repository"

                            ^
SyntaxError: Missing parentheses in call to 'print'

Thank you :)

**Comment by rbsec** [comment]
This isn't an issue with the fact it's on Windows; it's because CMSmap is designed for Python2, not Python3. Try installing Python2 on windows and see if that works for you.

**Comment by pedrodj** [comment]
Hi rbsec,

thank you for the answer: any suggestion to downgrade to Perl2 on Windows ? Now I'm using Active Perl latest release that run Perl 3 ;)

**Comment by rbsec** [comment]
I think you're confusing Python and Perl (two completely different languages). CMSMap is built on python.

Can you install 2.x and 3.x alongside each other, so just download and install ActivePython 2.7.8.10 (the current latest) and it should work.

**Comment by pedrodj** [comment]
Yes sorry,

my mistake: Python 2.7.9 installed


[I] Checking for Directory Listing Enabled ...
Traceback (most recent call last):
  File "cmsmap.py", line 1967, in <module>
    scanner.ForceCMSType()
  File "cmsmap.py", line 196, in ForceCMSType
    WPScan(self.url,self.threads).WPrun()
  File "cmsmap.py", line 383, in WPrun
    self.WPDirsListing()
  File "cmsmap.py", line 534, in WPDirsListing
    GenericChecks(self.url).DirectoryListing('/wp-content/plugins/'+plugin)
  File "cmsmap.py", line 1627, in __init__
    self.NotExisitingLength()
  File "cmsmap.py", line 1708, in NotExisitingLength
    htmltext = urllib2.urlopen(req).read()
  File "c:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "c:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "c:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] Impossibile stabilire la connessi
one. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppur
e mancata risposta dall'host collegato>

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
