### ISSUE TITLE
URL can't contain control characters [FIX]

### ISSUE THREAD

**Issue by erikandri** [Dionach/CMSmap#33]
https://github.com/dionach/CMSmap/blob/59dd0e2b3b0c751c6da2b0565374ab83c736b0e6/cmsmap/lib/requester.py#L29

When i run CMSMap and it's checking for Plugins, there is plugin path that have space in their name then program throw an exception "http.client.InvalidURL: URL can't contain control characters.", so i debug the line like below

Before:
self.response = urllib.request.urlopen(self.req, context=self.ctx)
self.response = urllib.request.urlopen(self.req)

After:
from urllib import parse
self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx)
self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'))

There is actually other 5 self.response, you can update all of them

**Comment by frav1s** [comment]
> https://github.com/dionach/CMSmap/blob/59dd0e2b3b0c751c6da2b0565374ab83c736b0e6/cmsmap/lib/requester.py#L29
> 
> When i run CMSMap and it's checking for Plugins, there is plugin path that have space in their name then program throw an exception "http.client.InvalidURL: URL can't contain control characters.", so i debug the line like below
> 
> Before: self.response = urllib.request.urlopen(self.req, context=self.ctx) self.response = urllib.request.urlopen(self.req)
> 
> After: from urllib import parse self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'))
> 
> There is actually other 5 self.response, you can update all of them

i updated but got the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
Exception in thread Thread-8:
Traceback (most recent call last):
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
Exception in thread Thread-10:
Traceback (most recent call last):
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_output(message_body, encode_chunked=encode_chunked)
    h.request(req.get_method(), req.selector, req.data, headers,
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self.send(msg)
    self.endheaders(body, encode_chunked=encode_chunked)
    self._send_request(method, url, body, headers, encode_chunked)
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 945, in connect
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 945, in connect
    self._send_output(message_body, encode_chunked=encode_chunked)
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.sock = self._create_connection(
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
  File "/usr/lib/python3.9/socket.py", line 823, in create_connection
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
  File "/usr/lib/python3.9/socket.py", line 823, in create_connection
    self.endheaders(body, encode_chunked=encode_chunked)
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self.connect()
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 945, in connect
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 945, in connect
  File "/usr/lib/python3.9/socket.py", line 823, in create_connection
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    self.send(msg)
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.sock = self._create_connection(
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
  File "/usr/lib/python3.9/socket.py", line 823, in create_connection
    self.connect()
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
  File "/usr/lib/python3.9/http/client.py", line 945, in connect
Traceback (most recent call last):
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    self.run()
  File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run
    self.sock = self._create_connection(
    requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None)
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    self.run()
  File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request
  File "/usr/lib/python3.9/socket.py", line 823, in create_connection
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None)
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx)
  File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request
    self.run()
  File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None)
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None)
    self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx)
    return opener.open(url, data, timeout)
  File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
  File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    return opener.open(url, data, timeout)
    self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx)
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    return opener.open(url, data, timeout)
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    response = self._open(req, data)
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    response = self._open(req, data)
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    result = self._call_chain(self.handle_open, protocol, protocol +
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = self._call_chain(self.handle_open, protocol, protocol +
    self.run()
  File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None)
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request
    result = func(*args)
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
    raise URLError(err)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx)
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    raise URLError(err)
    return self.do_open(http.client.HTTPConnection, req)
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    raise URLError(err)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by erikandri** [comment]
> > https://github.com/dionach/CMSmap/blob/59dd0e2b3b0c751c6da2b0565374ab83c736b0e6/cmsmap/lib/requester.py#L29
> > 
> > When i run CMSMap and it's checking for Plugins, there is plugin path that have space in their name then program throw an exception "http.client.InvalidURL: URL can't contain control characters.", so i debug the line like below
> > Before: self.response = urllib.request.urlopen(self.req, context=self.ctx) self.response = urllib.request.urlopen(self.req)
> > After: from urllib import parse self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'))
> > There is actually other 5 self.response, you can update all of them
> 
> i updated but got the following error: Traceback (most recent call last): File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open Exception in thread Thread-7: Traceback (most recent call last): File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open h.request(req.get_method(), req.selector, req.data, headers, File "/usr/lib/python3.9/http/client.py", line 1279, in request Exception in thread Thread-8: Traceback (most recent call last): h.request(req.get_method(), req.selector, req.data, headers, File "/usr/lib/python3.9/http/client.py", line 1279, in request Exception in thread Thread-10: Traceback (most recent call last): self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request Exception in thread Thread-9: Traceback (most recent call last): File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open h.request(req.get_method(), req.selector, req.data, headers, self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders h.request(req.get_method(), req.selector, req.data, headers, File "/usr/lib/python3.9/http/client.py", line 1279, in request self._send_output(message_body, encode_chunked=encode_chunked) h.request(req.get_method(), req.selector, req.data, headers, self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output File "/usr/lib/python3.9/http/client.py", line 1279, in request File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request File "/usr/lib/python3.9/http/client.py", line 1279, in request self.send(msg) self.endheaders(body, encode_chunked=encode_chunked) self._send_request(method, url, body, headers, encode_chunked) self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.9/http/client.py", line 974, in send self.send(msg) File "/usr/lib/python3.9/http/client.py", line 974, in send File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request self.connect() File "/usr/lib/python3.9/http/client.py", line 945, in connect self.connect() File "/usr/lib/python3.9/http/client.py", line 945, in connect self._send_output(message_body, encode_chunked=encode_chunked) self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output self.sock = self._create_connection( self.sock = self._create_connection( File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request File "/usr/lib/python3.9/socket.py", line 823, in create_connection self.send(msg) File "/usr/lib/python3.9/http/client.py", line 974, in send for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo File "/usr/lib/python3.9/socket.py", line 823, in create_connection self.endheaders(body, encode_chunked=encode_chunked) self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders self.connect() self.send(msg) File "/usr/lib/python3.9/http/client.py", line 945, in connect self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.9/http/client.py", line 974, in send for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output for res in _socket.getaddrinfo(host, port, family, type, proto, flags): self.sock = self._create_connection( File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo self.connect() File "/usr/lib/python3.9/http/client.py", line 945, in connect File "/usr/lib/python3.9/socket.py", line 823, in create_connection socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): self.send(msg) for res in _socket.getaddrinfo(host, port, family, type, proto, flags): File "/usr/lib/python3.9/http/client.py", line 974, in send self.sock = self._create_connection( socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> ```
> for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> ```
> 
> File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo File "/usr/lib/python3.9/socket.py", line 823, in create_connection self.connect() File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner File "/usr/lib/python3.9/http/client.py", line 945, in connect Traceback (most recent call last): for res in _socket.getaddrinfo(host, port, family, type, proto, flags): self.run() File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner self.run() File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run self.sock = self._create_connection( requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None) File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo self.run() File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run for res in _socket.getaddrinfo(host, port, family, type, proto, flags): File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request File "/usr/lib/python3.9/socket.py", line 823, in create_connection socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None) File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request self.run() File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None) for res in getaddrinfo(host, port, 0, SOCK_STREAM): requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None) self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) return opener.open(url, data, timeout) File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen File "/usr/lib/python3.9/urllib/request.py", line 517, in open File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo return opener.open(url, data, timeout) self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) response = self._open(req, data) File "/usr/lib/python3.9/urllib/request.py", line 534, in _open self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen File "/usr/lib/python3.9/urllib/request.py", line 517, in open File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen for res in _socket.getaddrinfo(host, port, family, type, proto, flags): return opener.open(url, data, timeout) result = self._call_chain(self.handle_open, protocol, protocol + File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> ```
> return opener.open(url, data, timeout)
> ```
> 
> File "/usr/lib/python3.9/urllib/request.py", line 517, in open File "/usr/lib/python3.9/urllib/request.py", line 517, in open response = self._open(req, data) File "/usr/lib/python3.9/urllib/request.py", line 534, in _open response = self._open(req, data) Traceback (most recent call last): File "/usr/lib/python3.9/urllib/request.py", line 534, in _open response = self._open(req, data) File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner result = self._call_chain(self.handle_open, protocol, protocol + result = func(*args) File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open File "/usr/lib/python3.9/urllib/request.py", line 534, in _open File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain result = self._call_chain(self.handle_open, protocol, protocol + self.run() File "/home/fravis/CMSmap/cmsmap/lib/threadscanner.py", line 30, in run result = self._call_chain(self.handle_open, protocol, protocol + File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain result = func(*args) File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open requester.request(self.url + self.pluginPath + plugin + self.pluginPathEnd, data=None) return self.do_open(http.client.HTTPConnection, req) File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain File "/home/fravis/CMSmap/cmsmap/lib/requester.py", line 29, in request result = func(*args) result = func(*args) File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open return self.do_open(http.client.HTTPConnection, req) raise URLError(err) File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open self.response = urllib.request.urlopen(url=parse.quote_plus(self.req.get_full_url(), safe=':/'), context=self.ctx) return self.do_open(http.client.HTTPConnection, req) File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open urllib.error.URLError: <urlopen error [Errno -2] Name or service not known> File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen raise URLError(err) return self.do_open(http.client.HTTPConnection, req) return opener.open(url, data, timeout) File "/usr/lib/python3.9/urllib/request.py", line 517, in open raise URLError(err) File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open urllib.error.URLError: <urlopen error [Errno -2] Name or service not known> raise URLError(err) urllib.error.URLError: <urlopen error [Errno -2] Name or service not known> urllib.error.URLError: <urlopen error [Errno -2] Name or service not known> response = self._open(req, data) File "/usr/lib/python3.9/urllib/request.py", line 534, in _open result = self._call_chain(self.handle_open, protocol, protocol + File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain result = func(*args) File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open return self.do_open(http.client.HTTPConnection, req) File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open raise URLError(err) urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

I have stored my changes on my repository, maybe you can try that https://github.com/erikandri/CMSMap.git

**Comment by orestescaminha** [comment]
@erikandri   Great job, man. You really fixed it. It ran smoothly, without errors!! Congratulations
