### ISSUE TITLE
unknown_error

### ISSUE THREAD

**Issue by rakeen09** [Dionach/CMSmap#35]
![image](https://cloud.githubusercontent.com/assets/10359412/6435740/5636c1c8-c0ce-11e4-9ce5-5ade7b996db7.png)

**Comment by pedrodj** [comment]
Works fine for me Enumerating Users but


[I] Checking for Directory Listing Enabled ...
Traceback (most recent call last):
File "cmsmap.py", line 1967, in 
scanner.ForceCMSType()
File "cmsmap.py", line 196, in ForceCMSType
WPScan(self.url,self.threads).WPrun()
File "cmsmap.py", line 383, in WPrun
self.WPDirsListing()
File "cmsmap.py", line 534, in WPDirsListing
GenericChecks(self.url).DirectoryListing('/wp-content/plugins/'+plugin)
File "cmsmap.py", line 1627, in init
self.NotExisitingLength()
File "cmsmap.py", line 1708, in NotExisitingLength
htmltext = urllib2.urlopen(req).read()
File "c:\Python27\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "c:\Python27\lib\urllib2.py", line 431, in open
response = self._open(req, data)
File "c:\Python27\lib\urllib2.py", line 449, in _open
'_open', req)
File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
result = func(*args)
File "c:\Python27\lib\urllib2.py", line 1227, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "c:\Python27\lib\urllib2.py", line 1197, in do_open
raise URLError(err)
urllib2.URLError: one. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppur
e mancata risposta dall'host collegato>

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
