### ISSUE TITLE
 except urllib2.HTTPError, e:

### ISSUE THREAD

**Issue by megasqrt** [Dionach/CMSmap#4]
win 7 x64
CMSmap-master>cmsmap.py -t https://example.com
  File "C:\Users\sqrt-home\Downloads\CMSmap-master\cmsmap.py", line 213
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax

**Comment by m7x** [comment]
which version of Python are you using?

**Comment by megasqrt** [comment]
Python version 3.4.2

2015-04-09 18:08 GMT+04:00 m7x <notifications@github.com>:

> which version of Python are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dionach/CMSmap/issues/4#issuecomment-91243226>.
>



-- 
С уважением
Корнилов Алексей
*kornilov.alexey1986@gmail.com <kornilov.alexey1986@gmail.com>*

**Comment by gopherproxy** [comment]
CMSmap is not compatible with Python 3x. You should run it with Python 2.7.9 instead - works for me on win 7 x64

**Comment by kenjoe41** [comment]
Changed most of the `except ExceptionType, e:` to `except ExceptioType as e:` which should work in both versions. But for compatibility with Python 3, also the print statements have to be taken care of and some other issues so it is bettr to use Python 2 for now.

**Comment by CorpOfHack** [comment]
pliz help to solve problem:

`Traceback (most recent call last):
  File "cmsmap.py", line 2033, in <module>
    scanner.ForceCMSType()
  File "cmsmap.py", line 196, in ForceCMSType
    JooScan(self.url,self.threads).Joorun()
  File "cmsmap.py", line 682, in Joorun
    bruter.Joorun()
  File "cmsmap.py", line 1341, in Joorun
    htmltext = opener.open(self.url+self.joologin).read()
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Authorization Required`
