### ISSUE TITLE
scan stopped in 24%

### ISSUE THREAD

**Issue by c0ldb00t3r** [Dionach/CMSmap#40]
[-] Interesting Directories/Files ... 
Exception in thread Thread-5:      |--                                         | ETA:  00:02:11  12.55 B/s
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./cmsmap.py", line 1185, in run
    noRedirOpener.open(req); self.pluginsFound.append(plugin)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
 
z.txt                          24% |||||||||||                                 | ETA:  00:02:12  10.04 B/s

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
