### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by ph1losof** [Dionach/CMSmap#7]
## Issue Details
CMSmap Version:  Newest
CMS Type:  scan
CMS Version:  Newest
Plugin Name:  
OS Information:  Kali linux 2018.2 debian

## Steps to reproduce the issue
python3 cmsmap.py -t lyceum.univer.kharkov.ua -f J -F noedb

Traceback (most recent call last):
  File "cmsmap.py", line 25, in <module>
    main()
  File "/root/CMSmap/cmsmap/main.py", line 84, in main
    initializer.threads = int(args.threads)
ValueError: invalid literal for int() with base 10: 'lyceum.univer.kharkov.ua'

## Expected behaviour 

Describe how CMSmap should have handled the issue

**Comment by m7x** [comment]
To help me to debug this issue, what is the version of Joomla (assuming that you are the owner or you have been authorised to test that site)?

**Comment by k0l0ss** [comment]
I had same issue, int fnc is calling arg.threads but not getting any value. change it
initializer.threads = 4
