### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by Dheeraj1420** [dionach/CMSmap#8]
./cmsmap.py http://gevpgkrb.ac.in
[-] Date & Time: 13/04/2019 20:23:16
Traceback (most recent call last):
  File "/root/Desktop/CMSmap/cmsmap/main.py", line 168, in main
    addr = socket.gethostbyname(urlparse(args.target).hostname)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cmsmap.py", line 25, in <module>
    main()
  File "/root/Desktop/CMSmap/cmsmap/main.py", line 180, in main
    msg = "Unable to resolve: " + scanner.url
TypeError: must be str, not NoneType

**Comment by Dheeraj1420** [comment]
help plz

**Comment by Dheeraj1420** [comment]
Thank you

**Comment by DavidBruchmann** [comment]
The imported socket library seems returning often unexpected values, therefore the script stops in most cases.  
So either a proper handling of the returned types has to be included or perhaps the version of `socket` changed.
But it seems `socket` is often not only returning "unexpected" but also *unreasonable* values - in other words wrong values, so it might be considerable to replace it completely if another version never returns better results. A reason for wrong return-values could be that parameters are used wrong, that should be checked before planning further steps.
